<table>
    <caption>${sheetName}</caption>
    <thead>
    <tr style="text-align: center;font-weight: bold">
        <td>盘点单号</td>
        <td>仓库名称</td>
        <td>盘点日期</td>
        <td>盘点人</td>
        <td>盘点结果</td>
        <td colspan="4">盘点备注</td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td string>34798935795423686656</td>
        <td>中易丽颜-药品库</td>
        <td>2021-01-13 15:25:17</td>
        <td>KK</td>
        <td>共盘点3个:3个盘盈</td>
        <td colspan="4" style="width:25px;">备注</td>
    </tr>
    </tbody>
</table>
<table>
    <caption>${sheetName}</caption>
    <thead>
    <tr style="text-align: center;font-weight: bold">
        <td>物资名称</td>
        <td>规格</td>
        <td>账面数量</td>
        <td>盘点数量</td>
        <td>库房单位</td>
        <td>盘点数量</td>
        <td>使用单位</td>
        <td>盈亏数量</td>
        <td>盈亏标志</td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>薄水补水面膜</td>
        <td>10片</td>
        <td>9盒9片</td>
        <td></td>
        <td>盒</td>
        <td></td>
        <td>片</td>
        <td>9盒9片</td>
        <td>盘盈</td>
    </tr>
    <tr>
        <td>鼻假体</td>
        <td>个</td>
        <td>2个0个</td>
        <td></td>
        <td>个</td>
        <td></td>
        <td>个</td>
        <td>2个0个</td>
        <td>盘盈</td>
    </tr>
    <tr>
        <td>肉毒素</td>
        <td>100u</td>
        <td>9支20U</td>
        <td></td>
        <td>支</td>
        <td></td>
        <td>U</td>
        <td>0支0U</td>
        <td></td>
    </tr>
    </tbody>
</table>